{% set version = "1.1.0" %}
{% set robin_map_commit = "68ff7325b3898fca267a103bad5c509e8861144d" %}

package:
  name: nanobind
  version: {{ version }}

source:
  url: https://github.com/wjakob/nanobind/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 03ef7500e6cbd7344167dd84ae9eafb5d3002608539352e7a4f7fdd179d9e367

build:
  noarch: python
  script: git clone https://github.com/Tessil/robin-map.git ext/robin_map && git -C ext/robin_map checkout {{ robin_map_commit }} && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - git
  run:
    - python >=3.8

test:
  requires:
    - python >=3.8
    - pip
  commands:
    - pip check
    - python -c "import nanobind; import os; assert os.path.isdir(nanobind.cmake_dir()) and os.path.isdir(nanobind.include_dir())"

about:
  home: https://github.com/wjakob/nanobind
  summary: Seamless operability between C++17 and Python
  description: |
    nanobind is a small binding library that exposes C++ types in Python and
    vice versa. It is reminiscent of Boost.Python and pybind11 and uses
    near-identical syntax. In contrast to these existing tools, nanobind is
    more efficient: bindings compile in a shorter amount of time, producing
    smaller binaries with better runtime performance.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/wjakob/nanobind

extra:
  recipe-maintainers:
    - MatthiasKohl
    - wjakob
